accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name="accounts"

urlpatterns = [
    re_path(r'login/$',
            auth_views.LoginView.as_view(template_name='accounts/login.html'), 
            name='login'),
    re_path(r'logout/$',
            auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'signup/$', views.SignUp.as_view(), name='signup'),

]

the_weather/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'__debug__/', include(debug_toolbar.urls))
    ]+urlpatterns

weather/urls.py
from django.urls import path, re_path
from . import views
app_name = 'weather'
urlpatterns = [
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('', views.IndexView.as_view(), name='home'),
    path('weather/', views.WeatherListView.as_view(), name = "weather"),
    #re_path(r'weather/(?P<slug>[-\w]+)/$', views.CityDeleteView.as_view(), name='delete'),
    re_path(r'^weather/(?P<pk>\d+)/delete/$', views.CityDeleteView.as_view(), name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

weather/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'countries'


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(unique=True, max_length=30)
    slug = models.SlugField(allow_unicode=True, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class SelectedCity(models.Model):
    city = models.ForeignKey(City, related_name='selected_city', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE)

    def __str__(self):
        return (self.user.username+"_"+self.city.name)

    class Meta:
        verbose_name_plural = 'selectedcities'
        unique_together = ('city','user')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    
    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

weather/forms.py
from django import forms
from .models import City, Country, SelectedCity
from django.contrib.auth import get_user_model

class CityForm(forms.ModelForm):
    country = forms.ModelChoiceField(queryset=Country.objects.all())
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        print(self.request)
        super(CityForm, self).__init__(*args, **kwargs)

    class Meta:
        model = SelectedCity
        fields = ['country','city']
    
    def clean(self):
        cleaned_data = super(CityForm, self).clean()
        city = cleaned_data.get('city')
        cities = SelectedCity.objects.prefetch_related('user').filter(user_id__exact = self.request.user.id)
        for c in cities:
            if city == c.city:
                raise forms.ValidationError(f'{city} is already added. Please select another city.')
        
            

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

the_weather/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name='accounts/test.html'


class ThanksPage(TemplateView):
    template_name='accounts/thanks.html'

weather/views.py
import requests
from django.urls import reverse_lazy, reverse
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import CreateView, TemplateView, DeleteView
from . import models
from .models import City, SelectedCity
from .forms import CityForm
from django.http import Http404
from django.contrib.auth import get_user_model
import os

# Create your views here.
User = get_user_model()
class IndexView(TemplateView):
    template_name='weather/index.html'

class WeatherListView(LoginRequiredMixin, CreateView):
    form_class = CityForm
    model = SelectedCity
    success_url = reverse_lazy('weather:weather')
    template_name = 'weather/weather.html'

    def get_form_kwargs(self):
        kwargs = super(WeatherListView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form_class):
        self.object = form_class.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form_class)

    def get_context_data(self, **kwargs):
        API_KEY=os.getenv('api_key')
        url = "http://api.openweathermap.org/data/2.5/weather?q={name}&units=imperial&appid={api}"
        try:
            cities = SelectedCity.objects.prefetch_related('user').filter(user_id__exact = self.request.user.id)
        except User.DoesNotExist:
            raise Http404
        else:
            weather_data = []
            for city in cities:
                r = requests.get(url.format(name=city.city, api=str(API_KEY))).json()
                print(r)
                city_weather = {
                    'id': city.id,
                    'city' : city.city.name,
                    'temperature' : r['main']['temp'],
                    'description' : r['weather'][0]['description'],
                    'icon' : r['weather'][0]['icon'],
                }
                weather_data.append(city_weather)
        context = super().get_context_data(**kwargs)
        context['weather_data']=weather_data
        return context


def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'weather/city_dropdown_list_options.html', {'cities': cities})


class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = models.SelectedCity
    success_url = reverse_lazy('weather:weather')

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% extends "weather/base.html" %}
{% load bootstrap3 %}
{% block body_block %}
<div class="container">
    <h1 class='title'>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% extends "weather/base.html" %}
{% load bootstrap3 %}
{% block body_block %}
<div class="container">
    <h1 class="title">Sign Up</h1>
    <form method="POST" class="form-group">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Sign Up">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/test.html
<!DOCTYPE html>
{% extends "weather/base.html" %}
{% block body_block %}
<h1>You are now Logged In!</h1>
{% endblock %}

accounts/templates/accounts/thanks.html
<!DOCTYPE html>
{% extends "weather/base.html" %}
{% block body_block %}
<h1>Thanks for Visiting, Come back soon!</h1>
{% endblock %}

weather/templates/weather/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Weather App</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://kit.fontawesome.com/f1c98c5c47.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <ul class="nav">
                    <li>
                        <a class="navbar-brand nav-item active font-weight-bold" href="{% url 'weather:home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link nav-item active font-weight-bold" href="{% url 'weather:weather' %}">Weather</a>
                    </li>
                    {% endif %}
                    <!-- <li><a class="nav-link nav-item active font-weight-bold" href="">Other</a></li> -->
                </ul>
                <ul class='nav justify-content-end'>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link nav-item active font-weight-bold" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link nav-item active font-weight-bold" href="{% url 'accounts:login' %}">Log In</a>
                    </li>
                    <li>
                        <a class="nav-link nav-item active font-weight-bold" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            <!-- Anything outside of this will be inherited if you extend -->
            {% endblock %}
        </div>
    </body>
</html>

weather/templates/weather/city_dropdown_list_options.html
<option value="">--------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

weather/templates/weather/index.html
<!DOCTYPE html>
{% extends "weather/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>This is your dashboard</h1>
</div>
{% endblock %}

weather/templates/weather/selectedcity_confirm_delete.html
<!DOCTYPE html>
{% extends "weather/base.html" %}
{% block body_block %}
    <h1>Delete {{ selectedcity.city.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'weather:weather' %}">Cancel</a>
    </form>
{% endblock %}

weather/templates/weather/weather.html
<!DOCTYPE html>
{% extends "weather/base.html" %}
{% load bootstrap3 %}
{% block body_block %}
<section class="section">
    <div class="container">
        <div class="jumbotron">
            <h1 class="title">
                What's the weather like?
            </h1>
                <form method="POST" id="personForm" data-cities-url="{% url 'weather:ajax_load_cities' %}" novalidate>
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit" class="button is-info">
                            Add City
                        </button>
                </form>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script>
                    $("#id_country").change(function () {
                    var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
                    var countryId = $(this).val();  // get the selected country ID from the HTML input

                    $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                        data: {
                        'country': countryId       // add the country id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                        }
                    });

                    });
                </script>
        </div>
    </div>
</section>


<section class="section">
    {% for city_weather in weather_data %}
    <div class="container"> 
        <div class="card bg-light mb-3 center" style="max-width: 25rem;">

            <div class="card-header">
                <div class="media">
                    <div class="media-middle media-left">
                        <a href="#">
                            <img class="media-left" src="http://openweathermap.org/img/w/{{ city_weather.icon }}.png" alt="Image">
                        </a>
                    </div>
                </div>
                <h1 class="text-middle font-weight-bold " style="font-size:40px">{{ city_weather.city }}</h1>
            </div>


            <div class="card-body">
              <h5 class="font-weight-bold">Temperature: {{ city_weather.temperature }} °F</h5>
              <br><p class="card-text font-weight-bold">{{ city_weather.description }}</p>
                <div class="text-right">
                <a type="button" href="{% url 'weather:delete' pk=city_weather.id %}">
                    <i class="far fa-trash-alt"></i>
                </a> 
                </div>                   
            </div>
        </div>
    </div>
                       
    
        {% endfor %}
</section>
{% endblock %}